[[exchanges]]
platform = "binance"
proxy = "socks5://127.0.0.1:1080"
url = "wss://stream.binance.com:9443/stream"

[[exchanges]]
platform = "bitstamp"
proxy = ""
url = "wss://ws.bitstamp.net:443"

# For each exchange, a source will be created for each market

[[markets]]
symbol = "ethbtc"

[[markets]]
symbol = "btcusdt"
